from __future__ import annotations

import os
import json
import torch
import torch.distributed as dist

from tqdm import trange
from pathlib import Path
from torch.nn import Module
from torch.optim import Optimizer
from torch.optim.lr_scheduler import LRScheduler
from diffusion_models.models.models import ScoreModel
from torch.utils.data import DataLoader, DistributedSampler
from diffusion_models.logging.utils import (
    build_run_logger,
    LogStatus,
    RunMetadataLogger,
)
from torch.nn.parallel import DistributedDataParallel as DDP
from diffusion_models.config.config import (
    RunConfig,
    ExperimentConfig,
    build_lr_scheduler,
    build_optimizer,
)


class Trainer:
    """
    Trainer for score-based diffusion models with optional DDP support.
    """

    model: ScoreModel
    """
    Model to train. Must implement `train_step`.
    """

    optimizer: Optimizer
    """
    Optimizer used for training.
    """

    file_path: str
    """
    Base path for saving weights and checkpoints.
    """

    device: torch.device
    """
    Device to use for training (e.g., 'cpu', 'cuda').
    """

    use_ddp: bool
    """
    Whether to use DistributedDataParallel (DDP) for multi-GPU training.
    """

    checkpoint_dir: str
    """
    Directory to save checkpoints.
    """

    weight_dir: str
    """
    Directory to save model weights (best weight and weight-history snapshots if enabled).
    """

    log_dir: str
    """
    Directory to save the per-run .log file. Defaults to `logs/runs/`.
    """

    def __init__(
        self,
        model: ScoreModel,
        optimizer: Optimizer,
        file_path: str,
        device: torch.device,
        use_ddp: bool = False,
        checkpoint_dir: str = "./data/checkpoints",
        weight_dir: str = "./data/weights",
        log_dir: str = "./logs/runs",
        metadata_csv_path: str = "./data/run_metadata.csv",
        save_weight_history: bool = False,
        weight_history_frequency: int = 10,
        lr_scheduler: LRScheduler | None = None,
        run_config: RunConfig | None = None,
    ):
        self.rank = int(os.environ.get("LOCAL_RANK", 0))
        self.world_size = int(os.environ.get("WORLD_SIZE", 1))
        self.file_path = file_path
        self.device = device
        self.checkpoint_frequency = 10
        self.use_ddp = False if str(device) == "mps" else use_ddp
        self.lr_scheduler = lr_scheduler
        self.run_config = run_config
        self.metadata_csv_path = metadata_csv_path
        self.save_weight_history = save_weight_history
        self.weight_history_frequency = weight_history_frequency

        checkpoint_dir = Path(checkpoint_dir)
        checkpoint_dir.mkdir(parents=True, exist_ok=True)

        weight_dir = Path(weight_dir)
        weight_dir.mkdir(parents=True, exist_ok=True)

        self.checkpoint = checkpoint_dir / f"{file_path}_ckpt.pt"
        self.weight_file = weight_dir / f"{file_path}_weights.pt"
        self.history_file = checkpoint_dir / f"{file_path}_history.json"
        self.log_file = Path(log_dir) / f"{file_path}.log"

        self.weight_history_dir = weight_dir / "history"
        if self.save_weight_history:
            self.weight_history_dir.mkdir(parents=True, exist_ok=True)

        self.logger = build_run_logger(file_path, self.log_file, rank=self.rank)

        self.epochs = 0
        self.history = []

        self._set_model(model, optimizer)

        # Record config that produced this run. Currently, won't write a metadata row
        # TODO: Let a config be constructed even if not generated by a yaml or external Config.
        if self.rank == 0 and self._current_config() is not None:
            RunMetadataLogger(self.metadata_csv_path).log_run(
                self._current_config(),
                run_id=file_path,
                log_file=self.log_file,
                status=LogStatus.STARTED,
            )

    def _unwrapped_model(self) -> Module:
        return self.model.module if self.use_ddp else self.model

    def _current_config(self) -> ExperimentConfig | None:
        return getattr(self._unwrapped_model(), "config", None)

    def _set_model(self, model: torch.nn.Module, optimizer: torch.optim.Optimizer):
        """
        Set the model and optimizer, load checkpoint if available, and wrap with DDP if needed.

        :param model: Model to train.
        :param optimizer: Optimizer for training.
        """
        self.model = model.to(self.device)
        self.optimizer = optimizer

        if self.checkpoint.exists():
            self._load_checkpoint()

        if self.use_ddp:
            self.model = DDP(self.model, device_ids=[self.rank])

    def _load_checkpoint(self):
        """
        Load model and optimizer state from checkpoint.
        """
        ckpt = torch.load(self.checkpoint, map_location=self.device, weights_only=True)
        model = self._unwrapped_model()
        model.load_state_dict(ckpt["MODEL_STATE"])
        self.epochs = ckpt["EPOCHS"]
        self.history = ckpt.get("HISTORY", [])

        # EMA safety
        if "EMA" in ckpt and hasattr(model, "exponential_moving_average"):
            model.exponential_moving_average.load_state_dict(ckpt["EMA"])

        self.logger.info(f"Loaded checkpoint: continuing from epoch {self.epochs}")

    def _save_checkpoint(self, epoch):
        """
        Save model and optimizer state to checkpoint.
        :param epoch: Current epoch number.
        """
        model = self._unwrapped_model()
        checkpoint = {
            "MODEL_STATE": model.state_dict(),
            "EPOCHS": epoch,
            "HISTORY": self.history,
        }
        if hasattr(model, "exponential_moving_average"):
            checkpoint["EMA"] = model.exponential_moving_average.state_dict()

        torch.save(checkpoint, self.checkpoint)
        self.logger.info(f"Epoch {epoch} | Checkpoint saved at {self.checkpoint}")

        with open(self.history_file, "w") as fp:
            json.dump(self.history, fp)

    def _save_weight_history(self, epoch: int):
        """
        Save weight snapshot for this epoch. Allows for comparison of weights along the training history.

        :param epoch: Current epoch number, used in snapshot's filename.
        :type epoch: int
        """
        model = self._unwrapped_model()
        path = self.weight_history_dir / f"{self.file_path}_weights_epoch{epoch:05d}.pt"
        model._save_weights(path)
        self.logger.info(f"Epoch {epoch} | Weight history snapshot saved at {path}")

    def _log_run_end(
        self, status: LogStatus, final_epoch: int, final_loss: float | None
    ):
        config = self._current_config()
        if config is None:
            return

        RunMetadataLogger(self.metadata_csv_path).log_run(
            config,
            run_id=self.file_path,
            log_file=self.log_file,
            status=status,
            final_epoch=final_epoch,
            final_loss=final_loss,
        )

    def train(
        self,
        loader: DataLoader,
        N_epochs: int | None = None,
        lr_scheduler: LRScheduler | None = None,
        early_stopping: int | None = None,
        min_delta: float | None = None,
    ):
        """
        Train the model using the provided DataLoader.

        :param loader: DataLoader for training data.
        :type loader: :class:`~torch.utils.data.DataLoader`
        :param N_epochs: Number of epochs to train for. Defaults to None.
        :type N_epochs: int | None
        :param lr_scheduler: Optional scheduler for adjusting learning rate. Defaults to None.
        :type lr_scheduler: :class:`~torch.optim.lr_scheduler.LRScheduler`
        :param early_stopping: Number of epochs with no improvement to wait before stopping. Defaults to None.
        :type early_stopping: int | None
        :param min_delta: Minimum change in loss to qualify as an improvement. Defaults to None.
        :type min_delta: float | None
        """
        if N_epochs is None:
            if self.run_config is None:
                raise ValueError(
                    "N_epochs must be given explicitly, or this Trainer must "
                    "have been built via Trainer.from_config"
                )
            N_epochs = self.run_config.N_epochs
        if lr_scheduler is None:
            lr_scheduler = self.lr_scheduler
        if early_stopping is None:
            early_stopping = self.run_config.early_stopping if self.run_config else 10
        if min_delta is None:
            min_delta = self.run_config.min_delta if self.run_config else 1e-4

        model = self._unwrapped_model()
        model.train()
        tqdm_epoch = trange(self.epochs, N_epochs, disable=(self.rank != 0))

        best_loss = float("inf")
        counter = 0
        last_epoch = self.epochs
        status = LogStatus.COMPLETED

        try:
            for epoch in tqdm_epoch:
                last_epoch = epoch
                epoch_loss = 0
                num_items = 0

                if hasattr(loader.sampler, "set_epoch"):
                    loader.sampler.set_epoch(epoch)

                for batch in loader:
                    labels = []
                    if isinstance(batch, (list, tuple)):
                        batch, labels = batch[0], batch[1:]

                    batch = batch.to(self.device)
                    labels = [l.to(self.device) for l in labels]

                    self.optimizer.zero_grad()

                    loss = model.train_step(
                        batch, self.optimizer, *labels, lr_scheduler=lr_scheduler
                    )

                    # DDP loss reduction
                    if self.use_ddp:
                        dist.all_reduce(loss, op=dist.ReduceOp.SUM)
                        loss = loss / self.world_size

                    # Logging only on rank 0
                    if self.rank == 0:
                        epoch_loss += loss.item() * batch.shape[0]
                        num_items += batch.shape[0]

                # Rank 0 decides whether to stop and checks with the remaining ranks.
                should_stop = torch.zeros(1, device=self.device)

                if self.rank == 0 and num_items > 0:
                    current_loss = epoch_loss / num_items
                    self.history.append(current_loss)

                    log_string = f"Epoch {epoch} | Average Loss: {current_loss:.6f}"

                    if epoch % self.checkpoint_frequency == 0:
                        self._save_checkpoint(epoch)

                    if (
                        self.save_weight_history
                        and epoch % self.weight_history_frequency == 0
                    ):
                        self._save_weight_history(epoch)

                    # Early stopping check
                    if best_loss - current_loss > min_delta:
                        counter = 0
                        best_loss = current_loss
                        model._save_weights(self.weight_file)
                        log_string += " ---> Best model so far (stored)"
                    else:
                        counter += 1

                    self.logger.info(log_string)
                    # tqdm_epoch.set_description(log_string)

                    if counter >= early_stopping:
                        self.logger.info(
                            f"Stopping training at epoch {epoch}! Best loss: {best_loss:.6f}"
                        )
                        should_stop.fill_(1)

                if self.use_ddp:
                    dist.broadcast(should_stop, src=0)

                if should_stop.item():
                    break

        except KeyboardInterrupt:
            status = LogStatus.INTERRUPTED
            self.logger.warning(f"Training interrupted by user at epoch {last_epoch}.")
            raise
        except Exception:
            status = LogStatus.FAILED
            self.logger.exception(f"Training failed at epoch {last_epoch}.")
            raise
        finally:
            if self.rank == 0:
                final_loss = (
                    best_loss
                    if best_loss != float("inf")
                    else (self.history[-1] if self.history else None)
                )
                self._log_run_end(
                    status=status, final_epoch=last_epoch, final_loss=final_loss
                )

    @classmethod
    def from_config(
        cls,
        model: ScoreModel,
        config: ExperimentConfig,
        device: str | torch.device | None = None,
    ) -> Trainer:
        model.config = config
        resolved_device = (
            device if device is not None else (config.model.device or model.device)
        )
        model.to(resolved_device)
        optimizer = build_optimizer(model, config.optimizer)
        lr_scheduler = build_lr_scheduler(optimizer, config.lr_scheduler)

        return cls(
            model=model,
            optimizer=optimizer,
            file_path=config.trainer.file_path,
            device=resolved_device,
            use_ddp=config.trainer.use_ddp,
            checkpoint_dir=config.trainer.checkpoint_dir,
            weight_dir=config.trainer.weight_dir,
            log_dir=config.trainer.log_dir,
            metadata_csv_path=config.trainer.metadata_csv_path,
            save_weight_history=config.trainer.save_weight_history,
            weight_history_frequency=config.trainer.weight_history_frequency,
            lr_scheduler=lr_scheduler,
            run_config=config.run,
        )
